# Generated by Django 5.0.3 on 2024-05-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM', '0003_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
