# Generated by Django 5.0.3 on 2024-05-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM', '0004_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
